version: "3.8"

services:
  mytail:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=$NODE_VERSION
        - PORT=$SERVER_PORT
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    volumes:
      - /var/log:/var/log
